<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{b051a9b6-3725-4d1f-b3dd-6053249d9316}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	timer : ULINT;
END_VAR
	]]></Declaration>
    <Implementation>
      <ST><![CDATA[timer := timer + 3;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>